export const newVocationalSkills = [
  {
    id: 'skill-trade-tiling',
    name: 'Floor & Wall Tiling Installation',
    slug: 'floor-wall-tiling-installation',
    category: 'Vocational & Technical Trades',
    description: 'Precision layout, surface preparation, adhesive application, cutting, leveling, and grouting for ceramic, porcelain, and marble tiles.',
    detailedDescription: 'Professional tiling involves reading architectural finishing drawings, checking subfloor level and screed moisture, establishing true 90-degree datum lines, selecting polymer-modified tile adhesives, executing diamond wet-saw miter cuts, operating tile-leveling clips, and applying chemical-resistant epoxy or cementitious grouts.',
    level: 'Beginner',
    demandLevel: 'Very High',
    whatItIsUsedFor: [
      'Installing porcelain, ceramic, and granite tiles in residential and commercial buildings',
      'Waterproofing and tiling bathrooms, wet rooms, swimming pools, and kitchen backsplashes',
      'Executing 45-degree mitered edges and bullnose trims for luxury architectural finishes',
      'Operating manual and electric diamond wet tile cutters with minimal material breakage'
    ],
    whyUsefulInGhana: 'Ghana’s booming residential real estate and commercial construction sectors in Accra, Kumasi, and Takoradi demand skilled tilers daily. Master tilers who deliver true lines, hollow-free installations, and flat surfaces command high daily rates and lucrative contract jobs on estate developments.',
    topCareers: ['Professional Tiler', 'Finishing Works Contractor', 'Tile Installation Foreman', 'Construction Finishes Inspector'],
    relatedJobs: ['Tile Layer', 'Bathroom Remodeler', 'Stone and Marble Mason'],
    industries: ['Building Construction', 'Real Estate Development', 'Interior Finishing & Renovation'],
    prerequisites: ['Attention to geometric alignment and manual dexterity'],
    toolsAndSoftware: ['Laser levels (360-degree)', 'Manual ceramic tile cutters (Rubi/Sigma)', 'Wet diamond saw', 'Notched adhesive trowels (6mm/10mm)', 'Tile leveling clips & wedges', 'Rubber grout floats'],
    relatedSkills: ['Masonry', 'Plumbing', 'Carpentry', 'Architectural Painting', 'Construction Safety'],
    certifications: ['National Vocational Training Institute (NVTI) Grade 1 & 2 Tiling Certificate', 'CTVET Level 3 Building Finishes', 'City & Guilds Construction Skills (Tiling)'],
    practicalProjects: [
      'Lay a 25-square-meter porcelain floor with zero lippage using a 360-degree laser level and leveling clips',
      'Execute a complete waterproofed walk-in shower wall tiling project with 45-degree mitered external corner joints',
      'Calculate an accurate material takeoff including tiles, adhesive bags, spacer clips, and grout for a 4-bedroom house'
    ],
    learningResources: [
      { title: 'NVTI Building Trades Tiling Curriculum', provider: 'National Vocational Training Institute (NVTI)', url: 'https://nvtighana.org', isFree: true },
      { title: 'Tiling Association Handbook and Standards', provider: 'The Tile Association', url: 'https://tiles.org.uk', isFree: true }
    ],
    source: 'Commission for TVET (CTVET) / National Vocational Training Institute (NVTI) Ghana',
    sourceUrl: 'https://ctvet.gov.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_workshop.jpg',
    imageAlt: 'Artisans installing precision floor and wall tiles using leveling systems on a construction site',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-trade-painting-pop',
    name: 'Architectural Painting, POP Ceilings & Screeding',
    slug: 'architectural-painting-pop-screeding',
    category: 'Vocational & Technical Trades',
    description: 'Plaster of Paris (POP) ceiling design, wall putty screeding, surface preparation, texture finishes, and airless spray painting.',
    detailedDescription: 'Architectural painting and ceiling finishing covers substrate preparation, chemical priming, multiple-pass wall putty screeding for glass-smooth finishes, structural framing and casting of Plaster of Paris (POP) and gypsum boards, decorative cornices, textured wall finishes, and application of emulsion, acrylic, and gloss coatings.',
    level: 'Beginner',
    demandLevel: 'Very High',
    whatItIsUsedFor: [
      'Framing, casting, and finishing modern POP recessed ceilings and lighting troughs',
      'Applying glass-smooth wall putty screeding to eliminate concrete plaster imperfections',
      'Operating airless paint sprayers for high-speed, uniform exterior and interior wall coating',
      'Applying specialized textured paints, stucco, and decorative feature wall effects'
    ],
    whyUsefulInGhana: 'Virtually all new private residences, commercial offices, and apartments in Ghana install decorative POP ceilings and screeded walls. High-end homeowners and contractors pay top dollar for artisans who produce smooth, crack-free ceilings and professional paint finishes.',
    topCareers: ['Architectural Painter', 'POP Ceiling Specialist', 'Interior Finishing Contractor', 'Decorative Coatings Artisan'],
    relatedJobs: ['Wall Screeder', 'Gypsum Ceiling Installer', 'Commercial Spray Painter'],
    industries: ['Building Construction', 'Real Estate', 'Interior Design & Renovation'],
    prerequisites: ['Steady hands and physical endurance for overhead work'],
    toolsAndSoftware: ['Airless paint spray rigs (Graco)', 'POP ceiling casting molds', 'Long screeding spatulas & trowels', 'Dustless drywall sanders with vacuum', 'Laser level markers'],
    relatedSkills: ['Interior Decoration', 'Tiling', 'Carpentry', 'Construction Safety', 'Color Theory'],
    certifications: ['NVTI Architectural Painting and Decorating Certificate', 'CTVET Level 3 Interior Finishing Technology', 'British Decorators Association Standard'],
    practicalProjects: [
      'Design, frame, and cast a modern suspended POP ceiling with hidden LED lighting troughs in a living room',
      'Apply a 2-coat full wall putty screeding over rough cement plaster and sand to a mirror-smooth finish',
      'Calculate paint quantities, primer, and thinning ratios for a 400-square-meter exterior building facade'
    ],
    learningResources: [
      { title: 'Painting and Decorating Manual', provider: 'NVTI Ghana', url: 'https://nvtighana.org', isFree: true },
      { title: 'POP and Gypsum Installation Guide', provider: 'CTVET Ghana', url: 'https://ctvet.gov.gh', isFree: true }
    ],
    source: 'National Vocational Training Institute (NVTI) / Commission for TVET (CTVET)',
    sourceUrl: 'https://ctvet.gov.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_workshop.jpg',
    imageAlt: 'Interior finishing artisans applying wall screeding and installing decorative POP ceilings',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-trade-motorcycle-mechanics',
    name: 'Motorcycle & Tricycle (Pragya) Mechanics & Diagnostics',
    slug: 'motorcycle-tricycle-mechanics',
    category: 'Vocational & Technical Trades',
    description: 'Maintenance, engine rebuilding, electrical wiring, carburetion, and brake servicing for commercial motorcycles and tricycles.',
    detailedDescription: 'Motorcycle and tricycle (Pragya / Aboboyaa) mechanics encompasses 4-stroke and 2-stroke small engines, clutch and transmission repair, carburetor tuning and cleaning, electronic ignition wiring, hydraulic disc and drum braking systems, wheel truing, and suspension rebuilding for commercial two- and three-wheelers.',
    level: 'Beginner',
    demandLevel: 'Very High',
    whatItIsUsedFor: [
      'Servicing, overhauling, and repairing passenger tricycles (Pragya) and cargo tricycles (Aboboyaa)',
      'Tuning carburetors, valve clearances, and spark ignition systems on delivery motorcycles',
      'Diagnosing charging system faults (stator coils, rectifiers, batteries) on commercial bikes',
      'Rebuilding motorcycle gearboxes, clutch plates, and final drive chains'
    ],
    whyUsefulInGhana: 'Commercial tricycles (Pragya) and cargo haulers (Aboboyaa) are the primary mode of transportation and goods distribution in cities like Kumasi, Tamale, Sunyani, Koforidua, and peri-urban Accra. Competent mechanics with clean diagnostic skills enjoy continuous daily cash earnings servicing commercial fleets.',
    topCareers: ['Motorcycle & Tricycle Mechanic', 'Fleet Maintenance Technician', 'Small Engine Repair Specialist', 'Spare Parts Retailer'],
    relatedJobs: ['Pragya Workshop Owner', 'Delivery Bike Fleet Mechanic', 'Motorcycle Auto-Electrician'],
    industries: ['Automotive & Transportation', 'Logistics & Delivery', 'Urban Mobility'],
    prerequisites: ['Mechanical aptitude and comfort working with grease and hand tools'],
    toolsAndSoftware: ['Motorcycle lift stands', 'Digital multimeters & timing lights', 'Carburetor ultrasonic cleaner', 'Flywheel pullers & valve spring compressors', 'Chain breaker & riveting tools'],
    relatedSkills: ['Automotive Diagnostics', 'Electrical Installation', 'Welding', 'Customer Relations', 'Small Engine Mechanics'],
    certifications: ['NVTI Motorcycle Mechanics Trade Certificate', 'CTVET Level 3 Two-and-Three Wheeler Automotive Technology', 'Ghana National Association of Garages (GNAG) Certification'],
    practicalProjects: [
      'Perform a complete top-end engine overhaul including piston ring replacement and valve lapping on a 150cc engine',
      'Troubleshoot and rewire a complete tricycle 12V electrical harness including lighting, horn, and charging circuit',
      'Service and bleed a hydraulic front disc brake system and replace rear mechanical brake shoes'
    ],
    learningResources: [
      { title: 'Small Engine and Motorcycle Mechanics Handbook', provider: 'NVTI Ghana', url: 'https://nvtighana.org', isFree: true },
      { title: 'Tricycle Maintenance Guidelines', provider: 'Ghana National Association of Garages', url: 'https://ctvet.gov.gh', isFree: true }
    ],
    source: 'National Vocational Training Institute (NVTI) / Ghana National Association of Garages',
    sourceUrl: 'https://nvtighana.org',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_workshop.jpg',
    imageAlt: 'Motorcycle mechanic diagnosing and repairing an engine in an automotive workshop in Ghana',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-trade-appliance-repair',
    name: 'Domestic Appliance Repair & Electronics Servicing',
    slug: 'domestic-appliance-repair-servicing',
    category: 'Vocational & Technical Trades',
    description: 'Diagnosing and repairing household electrical equipment (washing machines, microwaves, electric cookers, TVs, and blenders).',
    detailedDescription: 'Appliance repair trains technicians in electrical circuit tracing, power supply testing, motor capacitor replacement, switchgear and thermostatic control diagnosis, magnetron testing (microwaves), PCB soldering, inverter motor diagnostics, and safe domestic appliance earthing.',
    level: 'Beginner',
    demandLevel: 'Very High',
    whatItIsUsedFor: [
      'Diagnosing and replacing faulty heating elements, thermostats, and motors in home appliances',
      'Servicing automatic washing machines (drain pumps, inlet valves, drive belts, control boards)',
      'Safely troubleshooting high-voltage microwave ovens, air fryers, and electric ovens',
      'Repairing smart TVs, power boards, and audio equipment down to component level'
    ],
    whyUsefulInGhana: 'Ghanaians invest heavily in imported household appliances (Samsung, LG, Nasco, Midea). Replacement parts are costly and appliances fail frequently due to voltage fluctuations. Certified appliance technicians with diagnostic skills earn dependable incomes servicing homes and operating repair shops.',
    topCareers: ['Domestic Appliance Repair Technician', 'Electronics Service Specialist', 'Appliance Warranty Service Agent', 'Repair Workshop Owner'],
    relatedJobs: ['White Goods Technician', 'Audio-Visual Repairman', 'Small Appliance Fixer'],
    industries: ['Consumer Electronics', 'Repair & Maintenance', 'Retail & Warranty Services'],
    prerequisites: ['Basic physics and electrical safety understanding'],
    toolsAndSoftware: ['Digital multimeters (True RMS)', 'Soldering stations & desoldering pumps', 'Capacitance & ESR meters', 'Component component testers', 'High-voltage discharge probes'],
    relatedSkills: ['Electrical Installation', 'HVAC & Refrigeration', 'Customer Service', 'Electronics', 'Troubleshooting'],
    certifications: ['Energy Commission Domestic Electrical Appliance Inspector', 'CTVET Level 3 Consumer Electronics Servicing', 'City & Guilds Electronic Equipment Servicing'],
    practicalProjects: [
      'Diagnose and replace a failed main control PCB relay on an automatic front-loading washing machine',
      'Test and safely discharge a microwave high-voltage capacitor and replace a burnt magnetron',
      'Trace and solder failed surface-mount capacitors on an LED television power supply board'
    ],
    learningResources: [
      { title: 'Domestic Appliance Repair Guide', provider: 'NVTI Ghana', url: 'https://nvtighana.org', isFree: true },
      { title: 'Electrical Safety for Service Technicians', provider: 'Energy Commission of Ghana', url: 'https://energycom.gov.gh', isFree: true }
    ],
    source: 'Energy Commission of Ghana / Commission for TVET (CTVET)',
    sourceUrl: 'https://energycom.gov.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_workshop.jpg',
    imageAlt: 'Electronics technician testing circuit boards and repairing domestic household appliances',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-trade-aluminum-glazing',
    name: 'Aluminum Glazing & Modern Window Fabrication',
    slug: 'aluminum-glazing-metal-fabrication',
    category: 'Vocational & Technical Trades',
    description: 'Fabrication and installation of modern aluminum sliding windows, curtain walls, glass doors, and architectural storefronts.',
    detailedDescription: 'Aluminum fabrication involves architectural dimensioning, cutting aluminum profiles with precision miter saws, routing lock and drainage slots, assembling corner joints, rubber gasket fitting, glass handling (tempered, laminated, tinted), and securely anchoring window frames into masonry openings.',
    level: 'Beginner',
    demandLevel: 'Very High',
    whatItIsUsedFor: [
      'Fabricating and fitting sliding and casement aluminum windows for modern buildings',
      'Constructing tempered glass storefronts, office partitions, and shower enclosures',
      'Cutting, sealing, and installing laminated architectural safety glass',
      'Fabricating burglar-proof aluminum fly-screens and automated rolling shutters'
    ],
    whyUsefulInGhana: 'Traditional louver blades have been almost entirely replaced by modern sliding aluminum windows and glass partitions across residential and commercial buildings throughout Ghana. Fabricators who measure accurately and deliver watertight, rattle-free installations are constantly in high demand.',
    topCareers: ['Aluminum Fabricator', 'Glazing Contractor', 'Architectural Glass Installer', 'Fabrication Workshop Owner'],
    relatedJobs: ['Window Assembler', 'Storefront Installer', 'Glass Cutting Technician'],
    industries: ['Building Construction', 'Architecture & Glazing', 'Real Estate Finishing'],
    prerequisites: ['Spatial awareness and accuracy in millimeter measurement'],
    toolsAndSoftware: ['Aluminum miter chop saws with carbide blades', 'Pneumatic rivet guns', 'Profile copy routers', 'Glass suction vacuum lifters', 'Laser alignment levels'],
    relatedSkills: ['Structural Welding', 'Carpentry', 'Construction Safety', 'Tiling', 'Technical Drawing'],
    certifications: ['NVTI Architectural Metal & Aluminum Works Certificate', 'CTVET Level 3 Building Glazing Technology', 'Ghana Guild of Artisans Master Craftsman'],
    practicalProjects: [
      'Fabricate a 4-panel sliding aluminum window with integrated fly-screen and lock mechanism from raw profile extrusions',
      'Install a 10mm frameless tempered glass office partition with pivot glass door and floor spring',
      'Conduct an on-site dimensional survey and prepare an optimized profile cutting schedule to minimize aluminum waste'
    ],
    learningResources: [
      { title: 'Aluminum Fabrication and Glazing Manual', provider: 'NVTI Ghana', url: 'https://nvtighana.org', isFree: true },
      { title: 'Architectural Glazing Standards', provider: 'Ghana Standards Authority', url: 'https://gsa.gov.gh', isFree: true }
    ],
    source: 'National Vocational Training Institute (NVTI) / Ghana Standards Authority (GSA)',
    sourceUrl: 'https://nvtighana.org',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_workshop.jpg',
    imageAlt: 'Aluminum fabricators cutting profiles and assembling sliding glass windows in a workshop',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-trade-construction-safety',
    name: 'Building Construction Supervision & Site Safety (HSE)',
    slug: 'building-construction-site-safety',
    category: 'Vocational & Technical Trades',
    description: 'Site inspection, contractor coordination, scaffolding safety, occupational hazard control, and building code compliance.',
    detailedDescription: 'Construction supervision and Health, Safety & Environment (HSE) trains site leaders in structural drawing interpretation, concrete batch testing (slump test, cube test), scaffolding safety inspections, personal protective equipment (PPE) enforcement, excavation shoring, and accident prevention on building construction sites.',
    level: 'Intermediate',
    demandLevel: 'High',
    whatItIsUsedFor: [
      'Managing site activities, material logistics, and artisan coordination on active construction sites',
      'Conducting daily toolbox talks, hazard assessments, and enforcing safety standards',
      'Inspecting rebar reinforcement placement and concrete slump prior to structural casting',
      'Ensuring compliance with Ghana National Building Code (GS 1207:2018) standards'
    ],
    whyUsefulInGhana: 'With multi-story developments proliferating across Accra, Kumasi, and Takoradi, regulatory bodies (Inspectorate of Factories, Municipal Assemblies) and corporate developers demand certified site supervisors and safety officers to prevent structural collapses, worker accidents, and costly project delays.',
    topCareers: ['Construction Site Supervisor', 'Site Safety (HSE) Officer', 'Clerk of Works', 'Building Quality Inspector'],
    relatedJobs: ['Assistant Site Engineer', 'Safety Coordinator', 'Construction Foreman'],
    industries: ['Building Construction', 'Civil Engineering', 'Real Estate Development', 'Occupational Safety'],
    prerequisites: ['Experience in building trades or civil engineering background'],
    toolsAndSoftware: ['Concrete slump test cones & tamping rods', 'Digital laser distance meters', 'Scaffolding inspection tags', 'Safety hazard checklist apps', 'Personal protective equipment (PPE) audits'],
    relatedSkills: ['Masonry', 'Structural Welding', 'Project Management', 'Quality Assurance', 'First Aid'],
    certifications: ['Ghana National Building Code Compliance Certificate', 'NEBOSH International General Certificate in Occupational Health & Safety', 'GhIE Construction Technician Certificate'],
    practicalProjects: [
      'Conduct a comprehensive Job Hazard Analysis (JHA) and scaffolding inspection for a 3-story concrete building project',
      'Perform on-site concrete slump and cube test sampling for a suspended slab pour according to GSA standards',
      'Develop a site traffic management and deep excavation shoring plan for an urban construction footprint'
    ],
    learningResources: [
      { title: 'Ghana National Building Code Overview', provider: 'Ghana Standards Authority (GSA)', url: 'https://gsa.gov.gh', isFree: true },
      { title: 'Construction Safety and Health Guidelines', provider: 'Department of Factories Inspectorate Ghana', url: 'https://melr.gov.gh', isFree: true }
    ],
    source: 'Ghana Standards Authority (GSA) / Department of Factories Inspectorate Ghana',
    sourceUrl: 'https://gsa.gov.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_workshop.jpg',
    imageAlt: 'Construction site supervisor and safety officer inspecting concrete reinforcement on building site',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-trade-machine-operation',
    name: 'Industrial Machine Operation & Plant Safety',
    slug: 'machine-operation-plant-safety',
    category: 'Vocational & Technical Trades',
    description: 'Operation of industrial machinery, forklifts, hydraulic presses, conveyors, and automated packaging equipment in manufacturing plants.',
    detailedDescription: 'Machine operation covers pre-operational checks, Lockout/Tagout (LOTO) procedures, monitoring control panels, adjusting processing speeds, material feeding, diagnosing minor mechanical jams, industrial forklift driving, and complying with Factory Inspectorate safety protocols in manufacturing facilities.',
    level: 'Beginner',
    demandLevel: 'High',
    whatItIsUsedFor: [
      'Operating industrial production machines in beverage, plastics, cement, and food factories',
      'Driving counterbalanced warehouse forklifts for safe pallet movement and high-rack stacking',
      'Executing equipment startup, shutdown, and emergency stop protocols safely',
      'Performing basic Autonomous Maintenance (Total Productive Maintenance - TPM) cleaning and lubrication'
    ],
    whyUsefulInGhana: 'Industrial zones in Tema, North Industrial Area (Accra), Kumasi, and Takoradi host dozens of multinational and local factories (Nestlé, FanMilk, Kasapreko, Unilever, Wilmar). Certified machine and forklift operators are continually hired to maintain high factory throughput.',
    topCareers: ['Industrial Machine Operator', 'Certified Forklift Driver', 'Plant Operations Technician', 'Packaging Line Operator'],
    relatedJobs: ['Production Line Assistant', 'Warehouse Equipment Operator', 'Material Handler'],
    industries: ['Manufacturing & FMCG', 'Warehousing & Logistics', 'Packaging & Plastics', 'Food Processing'],
    prerequisites: ['Good hand-eye coordination and spatial judgment'],
    toolsAndSoftware: ['Industrial counterbalanced forklifts (DVLA licensed)', 'Hydraulic pallet jacks', 'Lockout/Tagout (LOTO) safety locks', 'Programmable Logic Controller (PLC) touchscreens', 'Digital tachometers'],
    relatedSkills: ['Supply Chain Logistics', 'Construction Safety', 'Electrical Servicing', 'Quality Assurance', 'Preventive Maintenance'],
    certifications: ['Driver and Vehicle Licensing Authority (DVLA) Forklift Operator License', 'Department of Factories Inspectorate Plant Safety Certificate', 'CTVET Level 3 Industrial Operations'],
    practicalProjects: [
      'Perform a certified 32-point pre-shift inspection and navigate an obstacle course with a counterbalanced forklift',
      'Execute an authorized Lockout/Tagout (LOTO) machine isolation protocol on an industrial packaging conveyor',
      'Record hourly production yield, downtime reasons, and reject rates on a computerized manufacturing logsheet'
    ],
    learningResources: [
      { title: 'Industrial Safety and Machine Operation', provider: 'Department of Factories Inspectorate Ghana', url: 'https://melr.gov.gh', isFree: true },
      { title: 'Forklift Operator Training Manual', provider: 'Driver and Vehicle Licensing Authority (DVLA)', url: 'https://dvla.gov.gh', isFree: true }
    ],
    source: 'Driver and Vehicle Licensing Authority (DVLA) / Department of Factories Inspectorate Ghana',
    sourceUrl: 'https://dvla.gov.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_workshop.jpg',
    imageAlt: 'Plant operator navigating a forklift and managing production machinery in a Tema industrial facility',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-trade-shoemaking',
    name: 'Bespoke Shoemaking & Footwear Craft',
    slug: 'bespoke-shoemaking-footwear',
    category: 'Vocational & Technical Trades',
    description: 'Pattern drafting, leather skiving, hand-lasting, stitching, welt construction, and sole finishing for custom leather shoes and native sandals.',
    detailedDescription: 'Shoemaking covers foot anatomy and sizing measurements, modifying shoe lasts, creating upper patterns, cutting and skiving genuine leather, stitching uppers on post-bed sewing machines, hand-lasting leather onto insoles, cementing or stitching outsoles (Goodyear welt / Blake stitch), and hand-burnishing soles and heels.',
    level: 'Beginner',
    demandLevel: 'High',
    whatItIsUsedFor: [
      'Crafting custom leather dress shoes (Oxfords, Derbies, Loafers) and royal Ghanaian sandals (Ahenema)',
      'Designing modern casual leather sneakers, boots, and orthotic footwear',
      'Executing upper pattern grading and leather skiving for production runs',
      'Repairing, resoling, and restoring high-end leather footwear'
    ],
    whyUsefulInGhana: 'Ghana has a proud tradition of leather craftsmanship and cultural footwear (e.g. Ashanti Ahenema royal sandals), alongside an exploding domestic market for locally made bespoke leather dress shoes and sandals. Skilled shoemakers in Kumasi, Accra, and Tamale build thriving brands catering to professionals, weddings, and export markets.',
    topCareers: ['Bespoke Shoemaker', 'Footwear Designer', 'Leather Footwear Brand Owner', 'Orthopedic Footwear Craftsman'],
    relatedJobs: ['Cobbler', 'Shoe Pattern Cutter', 'Leather Finisher'],
    industries: ['Footwear & Leatherworks', 'Fashion & Retail', 'Creative Crafts & Culture'],
    prerequisites: ['Patience and fine manual craftsmanship'],
    toolsAndSoftware: ['Wooden and plastic shoe lasts', 'Cobbler shoemaking hammers & lasting pincers', 'Heavy-duty post-bed leather sewing machines', 'Leather skiving knives', 'Pneumatic sole press machines'],
    relatedSkills: ['Leather Craft', 'Fashion Design', 'Branding', 'Pattern Cutting', 'Carpentry'],
    certifications: ['NVTI Leatherworks & Shoemaking Certificate', 'CTVET Level 3 Footwear Technology', 'Association of Footwear Manufacturers Ghana Accreditation'],
    practicalProjects: [
      'Construct a pair of handmade Goodyear-welted leather penny loafers from foot measurement to sole burnishing',
      'Handcraft a pair of authentic Ghanaian Ahenema royal sandals using carved wooden soles and embossed velvet/leather',
      'Grade and cut complete shoe upper patterns for European sizes 40 through 45'
    ],
    learningResources: [
      { title: 'Traditional and Modern Shoemaking Manual', provider: 'NVTI Ghana', url: 'https://nvtighana.org', isFree: true },
      { title: 'Footwear Craftsmanship in West Africa', provider: 'Ghana Export Promotion Authority (GEPA)', url: 'https://gepaghana.org', isFree: true }
    ],
    source: 'National Vocational Training Institute (NVTI) / Ghana Export Promotion Authority (GEPA)',
    sourceUrl: 'https://nvtighana.org',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_workshop.jpg',
    imageAlt: 'Ghanaian shoemaker crafting custom leather shoes and traditional sandals on wooden lasts',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-trade-leather-craft',
    name: 'Leather Craft & Bag Manufacturing',
    slug: 'leather-craft-bag-manufacturing',
    category: 'Vocational & Technical Trades',
    description: 'Designing, cutting, edging, stitching, and hardware assembly for genuine leather bags, wallets, belts, and accessories.',
    detailedDescription: 'Leather craft trains artisans in identifying leather grades (vegetable-tanned, chrome-tanned, suede, full-grain), precision hand-stitching (saddle stitch) and industrial machine sewing, edge burnishing with gum tragacanth, installing brass hardware (rivets, eyelets, zippers, buckles), and lining construction.',
    level: 'Beginner',
    demandLevel: 'High',
    whatItIsUsedFor: [
      'Manufacturing premium leather messenger bags, tote bags, and backpacks for retail and corporate gifts',
      'Crafting handmade bifold wallets, cardholders, and passport covers with fine edge burnishing',
      'Producing custom full-grain leather belts with solid brass buckles',
      'Combining traditional West African handwoven fabrics (Kente, Fugu) with genuine leather goods'
    ],
    whyUsefulInGhana: 'Made-in-Ghana leather goods, particularly fusions of northern leather and indigenous handwoven textiles, enjoy immense domestic popularity and strong export demand in the US and Europe under AGOA. Artisans with clean stitching and durable hardware command high export prices.',
    topCareers: ['Leather Goods Designer', 'Bag Manufacturer', 'Leather Accessory Brand Owner', 'Artisanal Leather Craftsman'],
    relatedJobs: ['Leather Stitcher', 'Pattern Cutter', 'Belt and Wallet Maker'],
    industries: ['Fashion Accessories', 'Leather Manufacturing', 'Export Handicrafts & AGOA', 'Retail'],
    prerequisites: ['Attention to detail and clean manual finishing'],
    toolsAndSoftware: ['Rotary hole punches & pricking irons (French style)', 'Saddle stitch sewing ponies', 'Edge bevelers & wooden slickers', 'Heavy-duty walking foot sewing machines', 'Hardware rivet setters'],
    relatedSkills: ['Shoemaking', 'Fashion Design', 'Pattern Cutting', 'Branding & Packaging', 'E-commerce'],
    certifications: ['CTVET Leather Craftsmanship Certification', 'GEPA Handicraft Export Quality Standard', 'NVTI Leather Goods Artisan Certificate'],
    practicalProjects: [
      'Hand-stitch a vegetable-tanned leather briefcase featuring a reinforced handle and brass buckle closure',
      'Produce a batch of 20 premium passport holders combining local handwoven Northern Fugu fabric and goat leather',
      'Execute a mirror-smooth beveled edge finishing and Tokonole burnish on thick saddle leather belts'
    ],
    learningResources: [
      { title: 'Leatherwork and Bag Making Guide', provider: 'NVTI Leather Unit', url: 'https://nvtighana.org', isFree: true },
      { title: 'Handicraft Export Quality Guidelines', provider: 'Ghana Export Promotion Authority (GEPA)', url: 'https://gepaghana.org', isFree: true }
    ],
    source: 'Ghana Export Promotion Authority (GEPA) Handicraft Directorate / NVTI Ghana',
    sourceUrl: 'https://gepaghana.org',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_workshop.jpg',
    imageAlt: 'Leather artisan stitching high-quality leather bags and accessories in a craft workshop',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-trade-bead-making',
    name: 'Traditional & Contemporary Bead Making & Jewelry Craft',
    slug: 'bead-making-jewelry-crafting',
    category: 'Vocational & Technical Trades',
    description: 'Recycled glass bead kiln firing, bead polishing, wire wrapping, and designing traditional and modern waist beads, necklaces, and jewelry.',
    detailedDescription: 'Bead craftsmanship covers the traditional Krobo recycled glass bead making process (crushing scrap glass, clay mold shaping, cassava leaf dye coloring, kiln firing), hand-grinding and polishing beads, wire-wrapping techniques, knotting, jewelry clasp assembly, and modern fashion jewelry styling.',
    level: 'Beginner',
    demandLevel: 'Growing',
    whatItIsUsedFor: [
      'Manufacturing authentic Ghanaian powdered glass beads and translucent recycled bottle beads',
      'Assembling traditional waist beads (Doma), royal necklaces, and ceremonial wristwear',
      'Designing contemporary bridal and evening jewelry integrating brass, cowries, and semi-precious stones',
      'Exporting authentic African beads to jewelry designers and cultural stores worldwide'
    ],
    whyUsefulInGhana: 'Beads hold deep cultural and aesthetic significance in Ghanaian society (rites of passage, royal durbars, festivals, waist adornment). Ghana’s Krobo beads are world-famous, generating significant income for artisans and exporters who sell to international tourists, local events, and online global marketplaces (Etsy).',
    topCareers: ['Bead Artisan & Manufacturer', 'Jewelry Designer', 'Cultural Accessories Entrepreneur', 'Handicraft Exporter'],
    relatedJobs: ['Bead Stringer', 'Waist Bead Stylist', 'Kiln Operator'],
    industries: ['Cultural Heritage & Crafts', 'Fashion Accessories & Jewelry', 'Tourism & Export'],
    prerequisites: ['Color appreciation, patience, and fine motor dexterity'],
    toolsAndSoftware: ['Traditional clay bead molds & cassava stalks', 'Wood-fired & gas ceramic kilns', 'Grinding stones with river sand & water', 'Jewelry pliers (round nose, chain nose, cutters)', 'Beading wire & elastic cords'],
    relatedSkills: ['Fashion Design', 'Interior Decoration', 'Cultural Heritage', 'Branding & E-commerce', 'Ceramics & Pottery'],
    certifications: ['Ghana Export Promotion Authority (GEPA) Cultural Craft Certification', 'Krobo Beadmakers Guild Master Artisan Badge', 'National Commission on Culture Accreditation'],
    practicalProjects: [
      'Mold, color, fire, and stone-polish a 100-piece batch of authentic Krobo powdered glass chevron beads',
      'Design and assemble a complete 3-piece bridal jewelry set (necklace, earrings, bracelet) using local beads and brass',
      'Package and label a collection of waist beads with cultural color symbolism documentation for online retail'
    ],
    learningResources: [
      { title: 'The Art of Ghanaian Glass Bead Making', provider: 'National Commission on Culture Ghana', url: 'https://ghanaculture.gov.gh', isFree: true },
      { title: 'Handicraft Export Directory and Quality Rules', provider: 'Ghana Export Promotion Authority (GEPA)', url: 'https://gepaghana.org', isFree: true }
    ],
    source: 'National Commission on Culture / Ghana Export Promotion Authority (GEPA)',
    sourceUrl: 'https://ghanaculture.gov.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_workshop.jpg',
    imageAlt: 'Artisans shaping and polishing traditional Ghanaian recycled glass beads in Krobo workshop',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-trade-soap-making',
    name: 'Artisanal Soap & Detergent Formulation',
    slug: 'artisanal-soap-detergent-production',
    category: 'Vocational & Technical Trades',
    description: 'Chemical saponification, cold-process and hot-process bar soaps, liquid hand soaps, multipurpose detergents, and FDA compliance.',
    detailedDescription: 'Soap and detergent production teaches oil fatty acid profiles (palm oil, coconut oil, shea butter, palm kernel oil), stoichiometric lye (NaOH & KOH) calculations, cold-process and hot-process saponification, surfactant chemistry for liquid detergents, essential oil scenting, curing room conditions, and packaging standards.',
    level: 'Beginner',
    demandLevel: 'Very High',
    whatItIsUsedFor: [
      'Manufacturing cold-process natural bar soaps enriched with local shea butter and neem oil',
      'Producing commercial liquid hand soaps, dishwashing liquids, and floor detergents for institutions',
      'Formulating authentic traditional black soap (Alata Samina) with cocoa pod ash and palm kernel oil',
      'Scaling up small-batch detergent production for supply to schools, hospitals, and cleaning services'
    ],
    whyUsefulInGhana: 'Soap and cleaning detergents are everyday consumables in high demand in Ghanaian homes, schools, offices, and restaurants. Starting an artisanal soap or liquid detergent enterprise requires minimal capital, uses locally abundant oils (shea butter, palm oil), and offers rapid profit margins.',
    topCareers: ['Soap & Detergent Formulator', 'Cosmetics Production Manager', 'Chemical Products Entrepreneur', 'Quality Assurance Assistant'],
    relatedJobs: ['Soapmaker', 'Detergent Compounder', 'Hygiene Product Distributor'],
    industries: ['FMCG & Chemical Products', 'Personal Care & Hygiene', 'Hospitality & Commercial Cleaning'],
    prerequisites: ['Adherence to chemical handling safety (goggles, gloves) and basic math'],
    toolsAndSoftware: ['Digital gram scales', 'Stainless steel mixing vessels & immersion blenders', 'Silicone bar soap loaf molds & wire cutters', 'pH indicator strips & digital meters', 'Lye safety protection gear'],
    relatedSkills: ['Natural Cosmetics Formulation', 'Food & Chemical Safety', 'Packaging & Branding', 'Business Management', 'Inventory Control'],
    certifications: ['Food and Drugs Authority (FDA) Cosmetics & Household Chemical Facility License', 'Ghana Standards Authority (GSA) Formulation Compliance', 'GEA Micro-Chemicals Training Certificate'],
    practicalProjects: [
      'Formulate and cure a 50-bar batch of nourishing 100% natural shea butter and honey cold-process soap with pH between 8.5-9.5',
      'Produce a 200-liter batch of high-viscosity commercial liquid dishwashing detergent using lab-calculated surfactants',
      'Prepare an FDA Product Registration Dossier including ingredient listing, batch sheet, and stability test documentation'
    ],
    learningResources: [
      { title: 'Soap and Detergent Manufacturing Guidelines', provider: 'Food and Drugs Authority Ghana', url: 'https://fdaghana.gov.gh', isFree: true },
      { title: 'Household Chemical Standards (GSA)', provider: 'Ghana Standards Authority', url: 'https://gsa.gov.gh', isFree: true }
    ],
    source: 'Food and Drugs Authority (FDA) Ghana / Ghana Standards Authority (GSA)',
    sourceUrl: 'https://fdaghana.gov.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_workshop.jpg',
    imageAlt: 'Formulators measuring ingredients and cutting cured artisanal shea butter soaps in facility',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-trade-natural-cosmetics',
    name: 'Natural Cosmetics & Shea Butter Product Formulation',
    slug: 'natural-cosmetics-shea-formulation',
    category: 'Vocational & Technical Trades',
    description: 'Formulating whipped shea body butters, hair balms, essential oil infusions, and facial creams compliant with international export standards.',
    detailedDescription: 'Cosmetics formulation covers emulsification, anhydrous balms, whipped butter technology, botanical extractions (moringa, baobab, neem), preservative efficacy testing, stability under tropical climates, and regulatory registration with the Food and Drugs Authority (FDA) and Global Shea Alliance export guidelines.',
    level: 'Beginner',
    demandLevel: 'Very High',
    whatItIsUsedFor: [
      'Producing luxury whipped shea body butters and hair pomades for local and international markets',
      'Formulating botanical lip balms, facial oils, and body scrubs using local brown sugar and coffee',
      'Operating small-batch natural skincare brands with high-end aesthetic packaging',
      'Exporting certified Grade-A unrefined and formulated shea cosmetics to Europe and North America'
    ],
    whyUsefulInGhana: 'Northern Ghana is the global heartland of premium shea butter production. Transforming raw shea nuts and butter into formulated, beautifully packaged, and FDA-registered body butters, lotions, and beard oils creates massive value addition and lucrative export sales.',
    topCareers: ['Skincare Formulator', 'Cosmetics Brand Founder', 'Natural Products Production Lead', 'Quality Control Specialist'],
    relatedJobs: ['Cosmetics Compounder', 'Product Development Specialist', 'Natural Beauty Entrepreneur'],
    industries: ['Cosmetics & Personal Care', 'Export & International Trade', 'Natural Wellness & Spa'],
    prerequisites: ['Commitment to precise measurement and clean laboratory hygiene'],
    toolsAndSoftware: ['Industrial planetary stand mixers (for whipped butters)', 'Double boiler melting tanks', 'Digital precision scales (0.01g)', 'pH meters & viscosity cups', 'Airless cosmetic jar filling stations'],
    relatedSkills: ['Artisanal Soap Making', 'Branding & Packaging', 'Clinical Skincare', 'E-commerce', 'Regulatory Compliance'],
    certifications: ['Food and Drugs Authority (FDA) Cosmetics Registration Certificate', 'Global Shea Alliance (GSA) Quality Formulator Certification', 'International Organic & Natural Cosmetics Standards (COSMOS)'],
    practicalProjects: [
      'Formulate a 10kg batch of non-greasy whipped body butter using raw shea butter, baobab oil, and arrowroot powder that stays stable at 35°C',
      'Conduct a 3-month accelerated heat stability and microbial challenge test on an anhydrous body balm',
      'Create an FDA-compliant product label including INCI chemical names, batch numbers, and expiry date coding'
    ],
    learningResources: [
      { title: 'Shea Butter Quality Guidelines', provider: 'Global Shea Alliance', url: 'https://globalshea.com', isFree: true },
      { title: 'Cosmetics Registration Requirements', provider: 'Food and Drugs Authority Ghana', url: 'https://fdaghana.gov.gh', isFree: true }
    ],
    source: 'Global Shea Alliance / Food and Drugs Authority (FDA) Ghana',
    sourceUrl: 'https://globalshea.com',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_workshop.jpg',
    imageAlt: 'Formulators whipping and packaging natural shea butter cosmetics in a clean production laboratory',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-trade-garment-production',
    name: 'Industrial Pattern Cutting & Garment Production',
    slug: 'garment-production-pattern-cutting',
    category: 'Vocational & Technical Trades',
    description: 'Precision pattern drafting, grading, cloth laying, industrial cutting, and assembly-line sewing for mass apparel manufacturing.',
    detailedDescription: 'Garment production trains technicians in technical flat pattern drafting, French curve grading across standard sizing charts (XS to 3XL), marker planning for fabric yield efficiency, operating industrial rotary fabric cutters, assembly-line section sewing, industrial overlock sergers, and quality assurance inspection for bulk garment export.',
    level: 'Intermediate',
    demandLevel: 'High',
    whatItIsUsedFor: [
      'Drafting and grading apparel patterns for industrial apparel factories under AGOA export orders',
      'Operating bulk cloth laying tables and electric rotary fabric cutting saws',
      'Managing production lines for school uniforms, corporate workwear, and fast fashion apparel',
      'Executing quality audits (stitch count per inch, measurement tolerances) on finished garments'
    ],
    whyUsefulInGhana: 'Under the African Growth and Opportunity Act (AGOA) and the emergence of major industrial apparel factories in Accra and Tema (e.g. Dignity DTRT, KAD Manufacturing), Ghana is rapidly becoming an apparel manufacturing hub for global brands (Nike, PVH). Skilled pattern cutters and production managers are in high demand.',
    topCareers: ['Pattern Maker & Grader', 'Garment Production Supervisor', 'Industrial Sewing Line Manager', 'Apparel Quality Assurance Lead'],
    relatedJobs: ['Sample Maker', 'Industrial Cutting Room Operator', 'Technical Apparel Specialist'],
    industries: ['Apparel Manufacturing', 'Fashion & Textiles', 'Export Manufacturing (AGOA)', 'Workwear & Uniforms'],
    prerequisites: ['Proficiency in basic sewing and accurate tape-measure geometry'],
    toolsAndSoftware: ['Industrial pattern grading curves (French curves & hip curves)', 'Rotary and vertical electric cloth cutting machines', 'Industrial heavy-duty overlock sergers (Juki/Brother)', 'Dress forms / tailor mannequins', 'Optitex / CLO 3D CAD pattern software'],
    relatedSkills: ['Fashion Design', 'Leather Craft', 'Supply Chain Management', 'Quality Assurance', 'Textile Science'],
    certifications: ['Commission for TVET (CTVET) Level 4 Garment Technology', 'NVTI Advanced Dressmaking & Industrial Tailoring Certificate', 'Association of Ghana Apparel Manufacturers (AGAM) Professional Endorsement'],
    practicalProjects: [
      'Draft a standard bodice, sleeve, and trouser block pattern and grade across five standard international sizes',
      'Execute an optimized fabric marker layout for 100 corporate polo shirts achieving 88%+ fabric utilization',
      'Set up an assembly line workflow for 20 industrial sewing machine operators producing school uniforms'
    ],
    learningResources: [
      { title: 'Garment Technology Manual', provider: 'Commission for TVET (CTVET) Ghana', url: 'https://ctvet.gov.gh', isFree: true },
      { title: 'AGOA Apparel Export Guide', provider: 'Association of Ghana Apparel Manufacturers (AGAM)', url: 'https://gepaghana.org', isFree: true }
    ],
    source: 'Commission for TVET (CTVET) / Association of Ghana Apparel Manufacturers (AGAM)',
    sourceUrl: 'https://ctvet.gov.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_workshop.jpg',
    imageAlt: 'Garment technicians working on industrial cutting tables and high-speed sewing production lines',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-trade-furniture-finishing',
    name: 'Furniture Spraying, Finishing & Upholstery',
    slug: 'furniture-finishing-upholstery',
    category: 'Vocational & Technical Trades',
    description: 'High-gloss and matte wood spraying, polyurethane staining, foam cutting, spring tying, and fabric upholstery for luxury furniture.',
    detailedDescription: 'Furniture finishing and upholstery teaches high-volume low-pressure (HVLP) spray gun operation, wood grain sealing, polyurethane and lacquer application, foam density selection (high-resilience foam), spring and webbing strapping, tufting (Chesterfield diamond tufting), and decorative piping and fabric stapling.',
    level: 'Beginner',
    demandLevel: 'High',
    whatItIsUsedFor: [
      'Spray-painting and staining bespoke dining tables, kitchen cabinets, and doors to factory-grade sheen',
      'Constructing and upholstering luxury sofas, armchairs, and tufted headboards with velvet and leather',
      'Re-upholstering and refurbishing automotive interiors, corporate office seating, and restaurant booths',
      'Applying heat- and moisture-resistant lacquer finishes on hardwood furniture'
    ],
    whyUsefulInGhana: 'Ghana has rich indigenous timber species (Teak, Mahogany, Wawa) and a booming market for locally crafted living room and bedroom furniture. Furniture makers who deliver smooth factory-grade spray finishes and plush, wrinkle-free upholstery can sell luxury sofas for thousands of Ghana cedis.',
    topCareers: ['Furniture Finishing Specialist', 'Master Upholsterer', 'Spray Painting Technician', 'Custom Furniture Studio Owner'],
    relatedJobs: ['Cabinet Sprayer', 'Automotive Upholsterer', 'Wood Staining Artisan'],
    industries: ['Furniture Manufacturing', 'Interior Design', 'Wood Processing', 'Automotive Customization'],
    prerequisites: ['Manual dexterity and keen eye for symmetrical fabric alignment'],
    toolsAndSoftware: ['HVLP gravity spray guns & air compressors', 'Pneumatic upholstery staple guns', 'Electric foam cutting saws', 'Webbing stretchers & tack pullers', 'Button tufting needles'],
    relatedSkills: ['Carpentry', 'Interior Decoration', 'Leather Craft', 'Construction Safety', 'Color Matching'],
    certifications: ['NVTI Woodwork & Upholstery Craft Certificate', 'CTVET Level 3 Furniture Finishing', 'Ghana Wood Association Master Craftsman'],
    practicalProjects: [
      'Spray a 6-seater solid mahogany dining table with sanding sealer and a 2-part polyurethane satin coat without runs',
      'Construct and upholster a 3-seater Chesterfield sofa with deep button diamond tufting and piped velvet cushions',
      'Refurbish and re-foam a set of 8 corporate executive office chairs with heavy-duty commercial fabric'
    ],
    learningResources: [
      { title: 'Wood Finishing and Upholstery Handbook', provider: 'NVTI Ghana', url: 'https://nvtighana.org', isFree: true },
      { title: 'Timber Industry Finishing Standards', provider: 'Timber Industry Development Division (TIDD)', url: 'https://fcghana.org', isFree: true }
    ],
    source: 'National Vocational Training Institute (NVTI) / Timber Industry Development Division (TIDD)',
    sourceUrl: 'https://nvtighana.org',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_workshop.jpg',
    imageAlt: 'Upholsterer stretching fabric and applying spray lacquer on custom furniture in Ghana',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  }
];
