export const newCreativeSkills = [
  {
    id: 'skill-creat-copywriting',
    name: 'Copywriting & Advertising Persuasion',
    slug: 'copywriting-advertising-persuasion',
    category: 'Creative Arts & Media',
    description: 'Direct response copywriting, billboard headlines, high-converting landing pages, email marketing, and social ad campaigns.',
    detailedDescription: 'Copywriting teaches behavioral psychology, proven direct-response frameworks (AIDA, PAS, BAB), emotional triggers, drafting magnetic headlines, writing high-converting landing pages, crafting email sales sequences, radio jingle scripts, billboard taglines, and A/B split-testing ad copy to drive sales in consumer and B2B markets.',
    level: 'Beginner',
    demandLevel: 'Very High',
    whatItIsUsedFor: [
      'Writing compelling ad copy for digital Facebook, Instagram, and Google ads that drive clicks and sales',
      'Drafting high-converting website landing pages and sales letters for Ghanaian e-commerce and startups',
      'Creating catchy taglines, radio commercial scripts, and billboard slogans for advertising agencies in Accra',
      'Authoring high-engagement email newsletters and promotional campaigns with high open and conversion rates'
    ],
    whyUsefulInGhana: 'As hundreds of Ghanaian businesses move online, the difference between a failing ad campaign and a multi-million cedi business is often the words used on the screen. Skilled copywriters who write persuasive copy that resonates culturally with Ghanaian consumers earn top remote salaries and client retainers.',
    topCareers: ['Senior Direct Response Copywriter', 'Advertising Creative Lead', 'Conversion Rate Copy Specialist', 'Freelance Commercial Copywriter'],
    relatedJobs: ['Ad Copywriter', 'Email Marketer', 'Content Strategist'],
    industries: ['Advertising & Marketing Agencies', 'E-commerce & Retail', 'Tech Startups & SaaS', 'Media & Publishing'],
    prerequisites: ['Love for language, empathy with human desires, and persuasive instinct'],
    toolsAndSoftware: ['Grammarly Business & Hemingway App', 'A/B testing ad copy spreadsheets', 'Swipe files of high-converting ads', 'Meta Ads Manager copy testing console'],
    relatedSkills: ['Digital Marketing', 'Creative Writing', 'Branding Strategy', 'SEO Content', 'Storytelling'],
    certifications: ['Advertising Association of Ghana (AAG) Copywriting Badge', 'American Writers & Artists Institute (AWAI) Direct-Response Certificate', 'CIMG Digital Copywriting Certification'],
    practicalProjects: [
      'Write a 5-part email nurture and promotional sequence that generates pre-orders for a new Ghanaian consumer brand launch',
      'Create 3 distinct billboard concepts with punchy 6-word headlines for a major Ghanaian telecom or fintech campaign',
      'Rewrite and A/B test a landing page sales letter, increasing projected conversion rates through stronger emotional hooks and benefits'
    ],
    learningResources: [
      { title: 'The Copywriter’s Handbook and Advertising Arts', provider: 'Advertising Association of Ghana (AAG)', url: 'https://aag.com.gh', isFree: true },
      { title: 'Direct Response Copywriting Fundamentals', provider: 'American Writers & Artists Institute (AWAI)', url: 'https://awai.com', isFree: true }
    ],
    source: 'Advertising Association of Ghana (AAG) / Chartered Institute of Marketing Ghana (CIMG)',
    sourceUrl: 'https://aag.com.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_seminar.jpg',
    imageAlt: 'Copywriter brainstorming advertising headlines and writing direct response marketing copy on laptop',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-creat-brand-storytelling',
    name: 'Narrative Storytelling & Brand Lore',
    slug: 'narrative-storytelling-brand-lore',
    category: 'Creative Arts & Media',
    description: 'Joseph Campbell hero journeys, founder brand mythologies, cultural heritage narratives, and emotionally resonant docu-stories.',
    detailedDescription: 'Brand storytelling teaches the art of myth-making and narrative architecture: transforming corporate missions into heroic human journeys, embedding Ghanaian cultural folklore and values (Ananse wisdom, resilience, communal ubuntu), structuring documentary case studies, and creating brand lore that builds lifelong emotional affinity with audiences.',
    level: 'Beginner',
    demandLevel: 'High',
    whatItIsUsedFor: [
      'Crafting founder origin stories and brand heritage narratives for Ghanaian enterprises and artisan brands',
      'Scripting emotional short-documentary videos showcasing real customer triumphs and impact stories',
      'Structuring nonprofit donor fundraising appeals that move hearts and inspire donations',
      'Developing corporate brand values and manifesto statements for global consumer brands'
    ],
    whyUsefulInGhana: 'Consumers in Ghana and across the African diaspora do not just buy products; they buy heritage, identity, and shared stories. Brands that ground themselves in compelling, culturally authentic narratives stand out dramatically from generic competitors.',
    topCareers: ['Chief Brand Storyteller', 'Narrative Brand Strategist', 'Creative Director', 'Documentary Brand Producer'],
    relatedJobs: ['Brand Lore Architect', 'Impact Communications Specialist', 'Creative Content Producer'],
    industries: ['Branding & Advertising', 'Creative Agencies', 'Nonprofit & Foundation Communications', 'Heritage & Culture'],
    prerequisites: ['Imagination, emotional sensitivity, and passion for indigenous storytelling'],
    toolsAndSoftware: ['Brand story canvas templates', 'Audio interview recorders', 'Story arc visual mapping boards (Milanote)', 'Screenplay formatters (Final Draft, WriterDuet)'],
    relatedSkills: ['Copywriting', 'Creative Writing', 'Videography', 'Public Speaking', 'Branding Strategy'],
    certifications: ['National Film and Television Institute (NAFTI) Brand Storytelling Certificate', 'CIMG Narrative Marketing Endorsement', 'African Narrative Collective Masterclass'],
    practicalProjects: [
      'Research and write a 1,500-word founder origin story for an artisanal Ghanaian shea butter or chocolate brand connecting local farmers to global luxury',
      'Develop a 3-minute video script following a single mother whose life was transformed by an educational scholarship program',
      'Create an integrated brand story archetype and manifesto document for a modern Ghanaian hospitality eco-resort'
    ],
    learningResources: [
      { title: 'The Craft of African Storytelling and Media', provider: 'UniMAC-NAFTI Film and Television Institute', url: 'https://nafti.edu.gh', isFree: true },
      { title: 'Narrative Marketing and Brand Strategy', provider: 'Chartered Institute of Marketing Ghana (CIMG)', url: 'https://cimghana.org', isFree: true }
    ],
    source: 'UniMAC-NAFTI Film and Television Institute / Ghana Journalists Association',
    sourceUrl: 'https://nafti.edu.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_seminar.jpg',
    imageAlt: 'Creative storyteller and brand strategist recording oral interviews and crafting brand narrative',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-creat-acting-performance',
    name: 'Acting & Stage Performance',
    slug: 'acting-stage-screen-performance',
    category: 'Creative Arts & Media',
    description: 'Character analysis, voice projection, Stanislavski method acting, improvisation, audition self-tapes, and screen performance.',
    detailedDescription: 'Acting and stage performance trains actors in script analysis, emotional memory, subtext, physical theatre, voice projection without strain, dialect and accent work, camera blocking, audition monologue delivery, self-tape production, and screen presence for feature films, television drama, and theatrical stage plays.',
    level: 'Beginner',
    demandLevel: 'High',
    whatItIsUsedFor: [
      'Performing lead and supporting roles in Ghanaian film (Gollywood/Ghallywood), television series, and streaming productions',
      'Acting in live stage drama productions at the National Theatre of Ghana and university playhouses',
      'Recording commercial advertisements, corporate educational training skits, and public awareness campaigns',
      'Producing audition self-tapes for international streaming platforms (Netflix, Showmax)'
    ],
    whyUsefulInGhana: 'Ghana has a storied theatrical and cinematic heritage (Efua Sutherland, Kwaw Ansah) and an expanding modern film industry producing content for global platforms like Netflix and Akwaaba Magic. Trained actors who master emotional depth, natural dialogue, and professional set discipline are consistently cast in major productions.',
    topCareers: ['Professional Film & Stage Actor', 'Commercial Voice & Screen Actor', 'Theatre Company Performer', 'Drama Coach'],
    relatedJobs: ['Supporting Actor', 'Voiceover Artist', 'Reenactment Performer'],
    industries: ['Film & Television Production', 'Theatre & Performing Arts', 'Advertising & Commercials'],
    prerequisites: ['Emotional vulnerability, physical expressiveness, and dedication to memorization and rehearsal'],
    toolsAndSoftware: ['Script annotation software', 'Self-tape audition ring light & smartphone camera mounts', 'Vocal warmup audio tracks', 'Lavalier microphones for self-tape auditions'],
    relatedSkills: ['Public Speaking', 'Voice Acting', 'Screenwriting', 'Dance & Movement', 'Emotional Intelligence'],
    certifications: ['National Theatre of Ghana Performance Certificate', 'UniMAC School of Performing Arts Acting Endorsement', 'Actors Guild of Ghana Professional Member'],
    practicalProjects: [
      'Deliver a compelling, nuanced 2-minute dramatic monologue for a camera self-tape audition exhibiting emotional arc and naturalism',
      'Perform a two-person stage scene from a celebrated Ghanaian theatrical play (e.g. The Marriage of Anansewa) with authentic dialect and blocking',
      'Participate in a 10-minute unscripted theatrical improvisation exercise maintaining character integrity under unexpected scene obstacles'
    ],
    learningResources: [
      { title: 'The Actor’s Craft and Theatrical Arts in Ghana', provider: 'National Theatre of Ghana', url: 'https://nationaltheatre.gov.gh', isFree: true },
      { title: 'Screen Acting Fundamentals', provider: 'UniMAC School of Performing Arts', url: 'https://nafti.edu.gh', isFree: true }
    ],
    source: 'National Theatre of Ghana / UniMAC School of Performing Arts',
    sourceUrl: 'https://nationaltheatre.gov.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_seminar.jpg',
    imageAlt: 'Actors rehearsing an expressive dramatic scene on the stage of the National Theatre of Ghana',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-creat-voice-acting-radio',
    name: 'Voice Acting & Radio Broadcasting',
    slug: 'voice-acting-radio-broadcasting',
    category: 'Creative Arts & Media',
    description: 'Diaphragmatic breath support, vocal timbre modulation, radio show hosting, audio commercials, audiobook narration, and animation dubbing.',
    detailedDescription: 'Voice acting and broadcasting covers diaphragmatic breath control, vocal warmups, microphone technique (proximity effect, pop filter use), pacing and inflection, sight-reading commercial voiceover copy, animated character voice creation, interviewing techniques for radio/podcast talk shows, and basic audio recording and editing in digital audio workstations.',
    level: 'Beginner',
    demandLevel: 'High',
    whatItIsUsedFor: [
      'Voicing high-impact commercial radio and TV advertisements for major brands and advertising agencies',
      'Hosting live radio programmes, sports commentary, and podcast talk shows across Ghana’s 500+ radio stations',
      'Narrating audiobooks, educational e-learning modules, and corporate documentary voiceovers',
      'Dubbing foreign films and providing character voices for animated cartoons and video games'
    ],
    whyUsefulInGhana: 'Radio is the most widely consumed medium in Ghana, spanning English and vibrant local-language stations (Twi, Ga, Ewe, Dagbani, Hausa). Distinctive, articulate, and charismatic voices are hired continually for radio hosting, station IDs, corporate commercials, and lucrative global remote voiceover jobs.',
    topCareers: ['Professional Voiceover Artist', 'Radio Presenter & On-Air Personality', 'Audiobook Narrator', 'Podcast Host & Producer'],
    relatedJobs: ['Radio Continuity Announcer', 'Commercial Jingle Voice', 'Animation Dubber'],
    industries: ['Radio Broadcasting & Podcasting', 'Advertising & Marketing', 'Audiobook Publishing', 'Animation & Film'],
    prerequisites: ['Pleasing vocal clarity, passion for oral expression, and good reading fluency'],
    toolsAndSoftware: ['Large-diaphragm studio condenser microphones (Rode NT1, Shure SM7B)', 'Audio interfaces (Focusrite Scarlett)', 'Audio editing software (Audacity, Adobe Audition)', 'Pop filters & acoustic reflection shields'],
    relatedSkills: ['Audio Engineering', 'Public Speaking', 'Acting', 'Podcasting', 'Creative Writing'],
    certifications: ['Ghana Broadcasting Corporation (GBC) Broadcast Training School Certificate', 'UniMAC Institute of Journalism Radio Presenter Diploma', 'Voice Actors Guild of Ghana Accreditation'],
    practicalProjects: [
      'Record, edit, and master a professional 60-second commercial voiceover demo reel showcasing three distinct emotional styles',
      'Host and produce a 15-minute live-style radio talk show segment including news headlines, an interview, and commercial breaks',
      'Narrate a 10-minute children’s audiobook chapter voicing 4 distinct character accents and emotional expressions'
    ],
    learningResources: [
      { title: 'Radio Broadcasting and Voice Craft', provider: 'Ghana Broadcasting Corporation (GBC) Training School', url: 'https://gbcghanaonline.com', isFree: true },
      { title: 'The Voiceover Artist Handbook', provider: 'UniMAC-GIJ Institute of Journalism', url: 'https://gij.edu.gh', isFree: true }
    ],
    source: 'Ghana Broadcasting Corporation (GBC) Training School / UniMAC-GIJ',
    sourceUrl: 'https://gbcghanaonline.com',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_seminar.jpg',
    imageAlt: 'Radio presenter speaking into a studio broadcast microphone in a modern Ghanaian radio station',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-creat-event-decoration',
    name: 'Event & Stage Decoration',
    slug: 'event-stage-decoration-styling',
    category: 'Creative Arts & Media',
    description: 'Draping architectural fabrics, balloon sculpting, stage backdrops, LED ambient lighting, floral centerpieces, and bridal stage design.',
    detailedDescription: 'Event decoration encompasses spatial dimensioning, theme conceptualization, structural fabric draping (ceiling swags, backdrop crossbars), balloon garlands and organic arches, artificial and fresh floral arrangements on pedestals, ambient LED uplighting, decorative furniture styling, and rapid event takedown logistics.',
    level: 'Beginner',
    demandLevel: 'Very High',
    whatItIsUsedFor: [
      'Designing breathtaking wedding reception stages, bridal head tables, and traditional engagement setups',
      'Styling corporate summit stages, award galas, and branded conference auditoriums across Ghana',
      'Constructing organic balloon arches and backdrops for birthday parties, anniversaries, and baby showers',
      'Transforming raw event grounds, church halls, and outdoor lawns into luxury fairytale settings'
    ],
    whyUsefulInGhana: 'Ghanaian weddings, celebrations, and corporate galas are visually spectacular, with families and corporations investing heavily in lavish event aesthetics. Creative decorators with fresh concepts, clean fabric draping, and dramatic lighting are booked back-to-back every weekend.',
    topCareers: ['Event Decorator & Stage Designer', 'Luxury Wedding Stylist', 'Event Decoration Enterprise Owner', 'Floral & Backdrop Specialist'],
    relatedJobs: ['Fabric Draping Specialist', 'Balloon Artist', 'Event Lighting & Props Coordinator'],
    industries: ['Events & Entertainment', 'Weddings & Lifestyle', 'Hospitality & Tourism', 'Visual Arts'],
    prerequisites: ['Color harmony sense, physical stamina, and creative eye for spatial scale'],
    toolsAndSoftware: ['Telescopic pipe and drape uprights & crossbars', 'Electric dual balloon inflator pumps & balloon sizing rings', 'LED wireless par uplights', 'Hot glue guns & zip tie fastening kits', 'Event mockup 3D software (Event Scene Pro)'],
    relatedSkills: ['Interior Decoration', 'Floristry', 'Event Planning', 'Color Theory', 'Lighting & Audio'],
    certifications: ['Event Decorators Association of Ghana (EDAG) Professional Certificate', 'CTVET Level 3 Event Styling Technology', 'Ghana Tourism Authority Approved Event Stylist'],
    practicalProjects: [
      'Design, erect, and illuminate a 20-foot seamless pleat fabric wedding backdrop with integrated floral arches and fairy lights',
      'Construct an organic 15-foot balloon arch with multiple balloon sizes (5", 11", 18", 36") and natural eucalyptus foliage',
      'Prepare a complete 3D color mood board, floor layout, and material rental budget for a 300-guest presidential gala'
    ],
    learningResources: [
      { title: 'Event Decoration and Stage Styling Manual', provider: 'Event Decorators Association of Ghana (EDAG)', url: 'https://visitghana.com', isFree: true },
      { title: 'Commercial Event Aesthetics Standards', provider: 'Ghana Tourism Authority (GTA)', url: 'https://visitghana.com', isFree: true }
    ],
    source: 'Event Decorators Association of Ghana (EDAG) / Ghana Tourism Authority',
    sourceUrl: 'https://visitghana.com',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_seminar.jpg',
    imageAlt: 'Event decorators arranging lush floral pedestals and elegant fabric draping on a luxury wedding stage',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-creat-interior-decoration',
    name: 'Interior Decoration & Space Styling',
    slug: 'interior-decoration-space-styling',
    category: 'Creative Arts & Media',
    description: 'Residential room staging, paint palettes, furniture layouts, window curtains, gallery walls, and Airbnb apartment styling.',
    detailedDescription: 'Interior decoration focuses on aesthetic enhancement of indoor spaces: space planning, choosing cohesive color schemes, selecting upholstery fabrics and floor rugs, designing custom window treatments (sheers, blackout drapes), curating indigenous African wall art and sculpture, staging Airbnb short-stay apartments, and residential client styling.',
    level: 'Beginner',
    demandLevel: 'High',
    whatItIsUsedFor: [
      'Staging and decorating modern residential apartments, villas, and family homes in urban Ghana',
      'Furnishing and styling luxury Airbnb short-term rental properties to command premium nightly rates',
      'Decorating executive corporate offices, boutique hotel lobbies, and trendy restaurants',
      'Consulting clients on paint palettes, lighting fixtures, curtain drapery, and furniture selection'
    ],
    whyUsefulInGhana: 'As real estate developers construct thousands of apartments and townhouses in Cantonments, Airport Residential, East Legon, and Kumasi, property buyers and Airbnb hosts increasingly hire interior decorators to transform bare concrete shells into stylish, welcoming luxury living spaces.',
    topCareers: ['Interior Decorator & Stylist', 'Residential Home Stager', 'Airbnb Interior Specialist', 'Home Decor Retailer'],
    relatedJobs: ['Space Planning Consultant', 'Soft Furnishings Stylist', 'Commercial Space Decorator'],
    industries: ['Interior Design & Real Estate', 'Home Furnishing & Retail', 'Short-Stay Hospitality (Airbnb)'],
    prerequisites: ['Aesthetic taste, spatial imagination, and client advisory skills'],
    toolsAndSoftware: ['SketchUp / Planner 5D room layout tools', 'Fabric and paint swatch fan decks', 'Laser distance meters & measuring tapes', 'Mood board collages (Canva, Milanote)'],
    relatedSkills: ['Event Decoration', 'Architectural Painting', 'Furniture Upholstery', 'Color Theory', 'Carpentry'],
    certifications: ['Ghana Interior Designers Association (GIDA) Certificate', 'Radford University College Interior Decorating Extension', 'British College of Interior Design Diploma'],
    practicalProjects: [
      'Complete a full interior styling concept and furniture sourcing budget for a 2-bedroom Airbnb apartment in Accra',
      'Design a cohesive color palette and soft furnishings scheme incorporating Ghanaian Kente accents and modern neutral tones',
      'Produce a to-scale 2D furniture floor plan layout optimizing natural lighting and traffic flow in a living/dining room'
    ],
    learningResources: [
      { title: 'Interior Decoration and Space Planning Manual', provider: 'Radford University College Department of Design', url: 'https://radford.edu.gh', isFree: true },
      { title: 'Ghanaian Interior Styling and Craft Integration', provider: 'Ghana Interior Designers Association', url: 'https://gsa.gov.gh', isFree: true }
    ],
    source: 'Radford University College Department of Design / Ghana Interior Designers Association (GIDA)',
    sourceUrl: 'https://radford.edu.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_seminar.jpg',
    imageAlt: 'Interior decorator reviewing fabric swatches and styling a modern living room in Accra',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-creat-drawing-sketching',
    name: 'Drawing, Pencil Sketching & Visual Arts',
    slug: 'drawing-sketching-visual-arts',
    category: 'Creative Arts & Media',
    description: 'Human figure anatomy, graphite and charcoal shading, perspective geometry, still life, and expressive visual art.',
    detailedDescription: 'Drawing and sketching is the foundation of all visual creativity. It covers proportional line drawing, contour mapping, 1-point and 2-point perspective, tonal shading with graphite (2H to 8B) and compressed charcoal, chiaroscuro lighting, human facial and body anatomy, and capturing quick urban life sketches in outdoor sketchbooks.',
    level: 'Beginner',
    demandLevel: 'High',
    whatItIsUsedFor: [
      'Creating commissioned realistic graphite and charcoal pencil portraits for clients and memorials',
      'Drafting conceptual rough sketches for fashion designers, architects, and storyboard animators',
      'Exhibiting and selling original drawings in art galleries, cultural festivals, and online',
      'Building foundational visual artistry required for digital illustration, sculpture, and graphic design'
    ],
    whyUsefulInGhana: 'Hand-drawn portrait commissions are immensely popular in Ghana for birthday gifts, weddings, and funeral memorial portraits. Furthermore, drawing is the essential foundational skill underpinning fashion design, digital concept art, 3D modeling, and fine art in Ghana’s thriving visual arts economy.',
    topCareers: ['Fine Artist & Portrait Sketcher', 'Concept Artist & Storyboarder', 'Visual Arts Instructor', 'Commercial Illustrator'],
    relatedJobs: ['Pencil Portrait Artist', 'Architectural Sketcher', 'Graphic Novel Inker'],
    industries: ['Fine Arts & Galleries', 'Publishing & Comics', 'Creative Advertising', 'Fashion & Architecture'],
    prerequisites: ['Patience, hand-eye coordination, and desire to observe reality closely'],
    toolsAndSoftware: ['Graphite pencils (graded 2H to 8B)', 'Vine & compressed charcoal sticks', 'Acid-free heavyweight drawing paper (Cartridge paper)', 'Tortillons & blending stumps', 'Kneaded erasers & fixative sprays'],
    relatedSkills: ['Digital Illustration', 'Fine Art Painting', 'Graphic Design', 'Fashion Design', 'Observation & Focus'],
    certifications: ['KNUST College of Art and Built Environment Fine Arts Certificate', 'Ghanatta College of Art and Design Diploma', 'Artists Alliance Gallery Emerging Artist Endorsement'],
    practicalProjects: [
      'Draw a realistic, anatomically accurate graphite pencil human portrait capturing lifelike skin texture and eyes',
      'Execute a 2-point perspective architectural drawing of a bustling Ghanaian street market scene with accurate light and shade',
      'Create a series of 10 rapid gestural charcoal figure sketches capturing human movement and dynamic posture'
    ],
    learningResources: [
      { title: 'Foundational Drawing and Composition Guide', provider: 'KNUST Department of Painting and Sculpture', url: 'https://knust.edu.gh', isFree: true },
      { title: 'Classical Sketching Techniques', provider: 'Ghanatta College of Art and Design', url: 'https://ghanaculture.gov.gh', isFree: true }
    ],
    source: 'KNUST Department of Painting and Sculpture / Ghanatta College of Art and Design',
    sourceUrl: 'https://knust.edu.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_seminar.jpg',
    imageAlt: 'Visual artist sketching a detailed realistic pencil portrait on an easel in art studio',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-creat-fine-art-painting',
    name: 'Fine Art Acrylic & Oil Painting on Canvas',
    slug: 'fine-art-painting-canvas',
    category: 'Creative Arts & Media',
    description: 'Canvas stretching, underpainting, palette knife impasto, color mixing, glazing, and producing African contemporary fine art.',
    detailedDescription: 'Fine art painting encompasses canvas stretching and gesso priming, color theory and pigment mixing, acrylic and oil medium dynamics, brushwork and palette knife impasto techniques, wet-on-wet blending, varnishing, and framing. It explores traditional and modern African themes (durbars, market women, abstract Afro-futurism, landscapes).',
    level: 'Beginner',
    demandLevel: 'High',
    whatItIsUsedFor: [
      'Producing original contemporary African paintings for private art collectors and corporate offices',
      'Exhibiting in prominent art galleries across Accra (Artists Alliance, Nubuke Foundation, Gallery 1957)',
      'Selling fine art prints, canvas originals, and murals to hotels, restaurants, and foreign tourists',
      'Executing large-scale public and private indoor/outdoor architectural murals'
    ],
    whyUsefulInGhana: 'Accra has emerged as one of the world’s most dynamic contemporary art hubs, attracting international curators, auction houses (Sotheby’s, Bonhams), and high-net-worth collectors. Talented Ghanaian painters celebrate local narratives, with successful artists commanding thousands of dollars per canvas.',
    topCareers: ['Professional Fine Artist & Painter', 'Muralist', 'Art Gallery Resident Artist', 'Visual Arts Educator'],
    relatedJobs: ['Canvas Painter', 'Art Restorer', 'Commissioned Mural Painter'],
    industries: ['Fine Arts & Galleries', 'Cultural Tourism', 'Interior Design & Architecture', 'Creative Economy'],
    prerequisites: ['Color appreciation, creative expression, and patience for multi-layered paint drying'],
    toolsAndSoftware: ['Stretched cotton and linen canvases', 'Artist-grade acrylic and oil paint sets', 'Palette knives & varied brush sets (flat, filbert, round)', 'Wooden artist studio easels', 'Varnish coatings (gloss/matte)'],
    relatedSkills: ['Drawing & Sketching', 'Color Theory', 'Digital Illustration', 'Interior Decoration', 'Art Curation'],
    certifications: ['KNUST Department of Painting and Sculpture Degree / Certificate', 'Artists Alliance Gallery Professional Exhibition Readiness', 'Nubuke Foundation Young Artist Fellowship'],
    practicalProjects: [
      'Stretch, prime with gesso, and paint a 3x4 foot original acrylic-on-canvas painting depicting Ghanaian cultural life',
      'Execute a rich multi-layered oil painting utilizing glazing techniques to achieve deep, luminous skin tones',
      'Design and paint a 10-meter vibrant indoor architectural wall mural for a commercial cafe or corporate atrium'
    ],
    learningResources: [
      { title: 'Contemporary Painting in West Africa', provider: 'KNUST Department of Painting and Sculpture', url: 'https://knust.edu.gh', isFree: true },
      { title: 'Visual Arts Exhibition and Career Standards', provider: 'Artists Alliance Gallery Ghana', url: 'https://artistsalliancegallery.com', isFree: true }
    ],
    source: 'Artists Alliance Gallery Ghana / KNUST Department of Painting and Sculpture',
    sourceUrl: 'https://artistsalliancegallery.com',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_seminar.jpg',
    imageAlt: 'Painter applying vibrant acrylic colors with a palette knife to a large canvas on an easel',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-creat-vocal-singing',
    name: 'Vocal Performance, Breathing & Choral Singing',
    slug: 'vocal-performance-singing',
    category: 'Creative Arts & Media',
    description: 'Diaphragmatic breath support, vocal pitch accuracy, chest/head voice blending, Gospel and Highlife harmonies, and stage presence.',
    detailedDescription: 'Vocal performance trains singers in diaphragmatic breath control, vocal warmups, expanding vocal range, pitch ear-training, tone resonance placement, belting safely without vocal cord strain, singing complex 4-part choral harmonies (Soprano, Alto, Tenor, Bass), and commanding stage presence for live musical performance.',
    level: 'Beginner',
    demandLevel: 'High',
    whatItIsUsedFor: [
      'Performing as lead or backing vocalists in church worship ministries and touring gospel choirs',
      'Recording commercial vocals for Afrobeats, Highlife, and Gospel music albums',
      'Singing live at corporate galas, private wedding ceremonies, and state music concerts',
      'Working as a commercial studio session singer recording advertising jingles'
    ],
    whyUsefulInGhana: 'Music and choral singing are intrinsic to Ghanaian cultural, spiritual, and social life. Churches, music bands, and gospel ministries invest heavily in trained vocalists. Singers who master pitch accuracy, vocal stamina, and harmonies are in constant demand for rehearsals, live recordings, and church ministries.',
    topCareers: ['Professional Vocalist & Singer', 'Choral Director', 'Backing Vocalist & Session Singer', 'Vocal Coach'],
    relatedJobs: ['Worship Leader', 'Studio Singer', 'Voice Instructor'],
    industries: ['Music Recording & Production', 'Church & Religious Ministries', 'Events & Live Entertainment'],
    prerequisites: ['Singing interest, musical ear, and willingness to practice daily vocal warmups'],
    toolsAndSoftware: ['Pitch pipes & chromatic digital keyboard tuners', 'Dynamic stage microphones (Shure SM58)', 'In-ear monitor systems (IEMs)', 'Metronome and vocal warmup exercise tracks'],
    relatedSkills: ['Music Production', 'Voice Acting', 'Public Speaking', 'Instrumental Musicianship', 'Emotional Expression'],
    certifications: ['Associated Board of the Royal Schools of Music (ABRSM) Singing Grade 1-8', 'University of Ghana School of Performing Arts Music Certificate', 'Musicians Union of Ghana (MUSIGA) Vocalist Accreditation'],
    practicalProjects: [
      'Execute a 4-octave vocal warmup routine demonstrating smooth transition between chest voice and head voice/falsetto',
      'Sing a lead vocal piece while maintaining perfect pitch across dynamic volume changes with live band accompaniment',
      'Direct and balance a 4-part harmony choral arrangement (SATB) for an authentic Ghanaian Highlife or Gospel hymn'
    ],
    learningResources: [
      { title: 'Vocal Pedagogy and African Choral Music', provider: 'University of Ghana Department of Music', url: 'https://ug.edu.gh', isFree: true },
      { title: 'ABRSM Singing Guidelines and Theory', provider: 'Associated Board of the Royal Schools of Music (ABRSM)', url: 'https://abrsm.org', isFree: true }
    ],
    source: 'University of Ghana School of Performing Arts / Musicians Union of Ghana (MUSIGA)',
    sourceUrl: 'https://ug.edu.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_seminar.jpg',
    imageAlt: 'Vocalist performing with passion into a microphone with backing choir in rehearsal studio',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-creat-instrumental-music',
    name: 'Instrumental Musicianship (Keyboard & Acoustic Guitar)',
    slug: 'instrumental-keyboard-guitar',
    category: 'Creative Arts & Media',
    description: 'Chords progression, fingerpicking, Highlife comping, Gospel organ playing, ear training, and live band performance.',
    detailedDescription: 'Instrumental musicianship teaches music theory fundamentals (scales, intervals, major/minor/diminished chords), chord progressions (2-5-1, Ghanaian Highlife turnaround rhythms), keyboard voicing and organ pedals, acoustic/electric guitar fingerpicking, strumming syncopation, playing by ear, and synchronizing with drummers and bassists in live ensembles.',
    level: 'Beginner',
    demandLevel: 'High',
    whatItIsUsedFor: [
      'Playing keyboard/piano or guitar in church worship bands, gospel ministries, and live Highlife bands',
      'Working as an in-demand studio session instrumentalist tracking guitar and piano on commercial records',
      'Accompanying solo singers at corporate acoustic sets, wedding receptions, and hotel lounges',
      'Teaching private instrument lessons to children and beginner adult music enthusiasts'
    ],
    whyUsefulInGhana: 'Every weekend, thousands of live music events, church services, and celebrations across Ghana require skilled keyboardists and guitarists. Instrument players with quick ear-transcription and deep groove pocket are continually booked and paid good honorariums for services and rehearsals.',
    topCareers: ['Professional Keyboardist / Pianist', 'Lead / Rhythm Guitarist', 'Live Band Music Director', 'Instrumental Music Teacher'],
    relatedJobs: ['Church Organist', 'Studio Session Player', 'Acoustic Guitarist'],
    industries: ['Live Entertainment & Bands', 'Church & Worship Ministries', 'Music Recording & Studios', 'Music Education'],
    prerequisites: ['Patience for finger muscle memory development and basic rhythmic sense'],
    toolsAndSoftware: ['61/88-key weighted digital keyboards (Yamaha/Roland)', 'Acoustic & electric guitars with amplifiers', 'Clip-on guitar tuners & capos', 'Metronome practice apps', 'Guitar tablature & sheet music readers'],
    relatedSkills: ['Music Production', 'Vocal Performance', 'Sound Engineering', 'Ear Training', 'Teamwork'],
    certifications: ['ABRSM Piano / Guitar Practical Grades', 'Musicians Union of Ghana (MUSIGA) Academy Certificate', 'University of Ghana Department of Music Diploma'],
    practicalProjects: [
      'Play standard Ghanaian Highlife guitar strumming rhythms and turnaround progressions seamlessly at 110 BPM',
      'Accompany a live singer through 5 standard gospel worship songs playing by ear using modern reharmonized chord extensions',
      'Sight-read a 32-bar musical score on keyboard and perform with accurate dynamic expression and rhythm'
    ],
    learningResources: [
      { title: 'The African Keyboard and Highlife Guitar Guide', provider: 'University of Ghana School of Performing Arts', url: 'https://ug.edu.gh', isFree: true },
      { title: 'Classical and Contemporary Musicianship', provider: 'ABRSM Music Theory', url: 'https://abrsm.org', isFree: true }
    ],
    source: 'University of Ghana Department of Music / Musicians Union of Ghana (MUSIGA)',
    sourceUrl: 'https://ug.edu.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_seminar.jpg',
    imageAlt: 'Musician playing chords on an acoustic guitar alongside a keyboardist in music rehearsal',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-creat-floristry',
    name: 'Floristry & Fresh Flower Arrangement',
    slug: 'floristry-floral-arrangement',
    category: 'Creative Arts & Media',
    description: 'Floral conditioning, bridal bouquets, table centerpieces, floral arches, wreath construction, and tropical flower design.',
    detailedDescription: 'Floristry covers selecting and conditioning fresh-cut flowers (roses, lilies, chrysanthemums, tropical bird-of-paradise, heliconias, foliage), floral foam hydration, spiraling hand-tied bridal bouquets, designing oasis floral foam table runners, boutonnières, sympathy floral wreaths, and temperature storage to prolong fresh flower lifespan in tropical heat.',
    level: 'Beginner',
    demandLevel: 'Growing',
    whatItIsUsedFor: [
      'Crafting fresh bridal bouquets, corsages, and boutonnières for luxury weddings across Ghana',
      'Designing exotic fresh floral arrangements for 5-star hotel lobbies, embassies, and corporate desks',
      'Constructing grand floral funeral wreaths and condolence flower baskets',
      'Operating boutique floral delivery gift businesses for Valentine’s Day, Mother’s Day, and birthdays'
    ],
    whyUsefulInGhana: 'Fresh flower gifting and luxury floral event decoration are experiencing rapid growth in urban Ghana. Clients pay substantial sums for beautifully conditioned fresh floral bouquets and lavish wedding table centerpieces that remain perky and fragrant throughout long events.',
    topCareers: ['Professional Florist', 'Floral Designer & Stylist', 'Flower Shop Entrepreneur', 'Event Floral Coordinator'],
    relatedJobs: ['Floristry Assistant', 'Floral Delivery Stylist', 'Fresh Flower Conditioning Attendant'],
    industries: ['Floristry & Horticulture', 'Weddings & Luxury Events', 'Gift Retail & E-commerce', 'Hospitality Decor'],
    prerequisites: ['Color appreciation, gentle handling, and care for natural botanical products'],
    toolsAndSoftware: ['Professional floral shears & stem strippers', 'Oasis wet floral foam blocks & floral tape', 'Floral preservative nutrient packets', 'Hydration flower conditioning buckets & vases'],
    relatedSkills: ['Event Decoration', 'Interior Decoration', 'Horticulture', 'Branding & Packaging', 'Color Theory'],
    certifications: ['Ghana Florists Guild Professional Floristry Certificate', 'Parks and Gardens Horticultural Floral Art Endorsement', 'British Floral Association (BFA) Foundation Certificate'],
    practicalProjects: [
      'Construct a hand-tied cascading spiral bridal bouquet using white roses, baby’s breath, and eucalyptus bound in satin ribbon',
      'Create a 3-foot elevated fresh floral centerpiece arrangement for a banquet table with balanced 360-degree viewing',
      'Formulate a post-harvest floral conditioning and hydration solution that keeps imported fresh roses hydrated for 7+ days'
    ],
    learningResources: [
      { title: 'Commercial Floristry and Flower Conditioning Guide', provider: 'Department of Parks and Gardens Ghana', url: 'https://visitghana.com', isFree: true },
      { title: 'The Professional Florist Handbook', provider: 'Ghana Florists Guild', url: 'https://gepaghana.org', isFree: true }
    ],
    source: 'Department of Parks and Gardens Ghana / Ghana Florists Guild',
    sourceUrl: 'https://visitghana.com',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_seminar.jpg',
    imageAlt: 'Florist hand-tying fresh roses and tropical foliage into an elegant bridal bouquet',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  },
  {
    id: 'skill-creat-dance-choreography',
    name: 'Cultural & Contemporary Dance Choreography',
    slug: 'dance-cultural-choreography',
    category: 'Creative Arts & Media',
    description: 'Traditional Ghanaian cultural dances (Adowa, Kpanlogo, Agbadza, Bamaya), Afro-dance routines, and music video choreography.',
    detailedDescription: 'Dance choreography covers traditional Ghanaian folk dances (rhythms, hand symbolism, footwork of Adowa, Kpanlogo, Agbadza, Kundum, Bamaya), contemporary African urban dance (Afrobeats, Amapiano), stage spatial awareness, blocking group dancers, timing choreography to polyrhythmic percussion, and directing live theatrical performance.',
    level: 'Beginner',
    demandLevel: 'High',
    whatItIsUsedFor: [
      'Performing and choreographing for national cultural troupes, state durbars, and tourism festivals',
      'Directing dance routines for chart-topping Afrobeats music videos and major concert stages',
      'Teaching cultural dance and African fitness classes to local youth, expatriates, and tourists',
      'Directing theatrical dance dramas at the National Theatre and international performing arts festivals'
    ],
    whyUsefulInGhana: 'Dance is one of Ghana’s most celebrated cultural exports (from traditional royal dances to globally trending viral dance moves like Azonto, Shaku, and contemporary Afro-dance). Professional choreographers and cultural dance troupes earn consistent income performing at national functions, weddings, festivals, and music tours.',
    topCareers: ['Professional Choreographer', 'Cultural Dance Performer', 'Dance Troupe Artistic Director', 'Afro-Dance Fitness Instructor'],
    relatedJobs: ['Music Video Dancer', 'Theatre Dance Ensemble Member', 'Cultural Dance Instructor'],
    industries: ['Performing Arts & Theatre', 'Music & Entertainment', 'Tourism & Cultural Heritage', 'Fitness & Wellness'],
    prerequisites: ['Rhythm awareness, physical stamina, and passion for expressive movement'],
    toolsAndSoftware: ['Traditional percussion instruments (Fontomfrom, Atumpan, Gome, Djembe)', 'Dance rehearsal studio mirrors & sound systems', 'Choreography formation blocking notebooks'],
    relatedSkills: ['Acting & Performance', 'Music Production', 'Vocal Performance', 'Physical Fitness', 'Storytelling'],
    certifications: ['National Dance Company of Ghana Certification', 'UniMAC School of Performing Arts Dance Diploma', 'Ghana Dancers Association Professional Member'],
    practicalProjects: [
      'Choreograph and perform an authentic 5-minute cultural suite combining Adowa and Kpanlogo dances with live drumming',
      'Direct a synchronized 8-person commercial Afro-dance routine for an energetic Afrobeats music video production',
      'Design and facilitate a 60-minute Afro-dance cardio wellness workshop celebrating traditional Ghanaian rhythms'
    ],
    learningResources: [
      { title: 'Traditional Dances of Ghana: History and Form', provider: 'National Dance Company / National Theatre of Ghana', url: 'https://nationaltheatre.gov.gh', isFree: true },
      { title: 'Contemporary Dance and Choreography in Africa', provider: 'UniMAC School of Performing Arts', url: 'https://nafti.edu.gh', isFree: true }
    ],
    source: 'National Dance Company of Ghana / National Theatre of Ghana',
    sourceUrl: 'https://nationaltheatre.gov.gh',
    verificationStatus: 'verified',
    lastVerifiedAt: '2026-03-20T00:00:00Z',
    imageUrl: '/images/institutions/ug_students_seminar.jpg',
    imageAlt: 'Cultural dancers in vibrant traditional attire performing an expressive Ghanaian dance routine',
    status: 'published',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-03-20T00:00:00Z'
  }
];
